apiVersion: batch/v1
kind: Job
metadata:
  name: secret-job-updating-job
spec:
  template:
    spec:
      containers:
      - name: pre-install-v05
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", {{.Files.Get "scripts/run.sh" }}]
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0

  backoffLimit: 3
  completions: 1
  parallelism: 1
